### ISSUE TITLE
How critical is the "latest" symlink to the functioning of pgBackRest?

### ISSUE THREAD

**Issue by RonJohn2** [pgbackrest/pgbackrest#2673]
PG 16.10, since that's what the application is certified for.
pgBackRest 2.56.0

To protect against ransomware, my company has decreed that ExaGrid NAS shares must be used for database backups, because (behind the scenes) it's filesystem is immutable.  Thus, while we can compress and delete (and even encrypt) files, the files still exist.

The problem is that, as a consequence, ExaGrid's filesystem does not support links (neither hard or sym). "pgbackrest backup" fails at the very end when creating the symlink to _latest_.

```
[snip]
2025-08-22 13:59:51.097 P00 DETAIL: wrote 'backup_label' file returned from backup stop function
2025-08-22 13:59:51.097 P00   INFO: check archive for segment(s) 0000000100000001000000E8:0000000100000001000000E8
2025-08-22 13:59:51.200 P00   INFO: new backup label = 20250822-135935F
2025-08-22 13:59:51.310 P00  ERROR: [041]: unable to create symlink '/Database/backups/pgbackrest/backup/nfs/latest' to '20250822-135935F': [524] Unknown error 524
2025-08-22 13:59:51.310 P00   INFO: backup command end: aborted with exception [041]
```

Is the "latest" symlink just a handy feature for DBAs, or is it integral to the design?

I'm hoping that a switch could be added to suppress it's creation.

**Comment by RonJohn2** [comment]
I _really_ want to keep using pgbr, since It Just Works, and does on-the-fly encryption, and that's another corporate requirement.

**Comment by dwsteele** [comment]
> To protect against ransomware, my company has decreed that ExaGrid NAS shares must be used for database backups, because (behind the scenes) it's filesystem is immutable. Thus, while we can compress and delete (and even encrypt) files, the files still exist.

That sounds like a well-designed immutable feature. We've seen too many vendors that implemented this by just forbidding deletes and overwrites. What a mess.

How do you get data back? Can they mount the storage for you at a point in time? Just curious. You might also want to have a look at how we have implemented this functionality on object stores: https://pgbackrest.org/user-guide.html#repo-target-time. 

> Is the "latest" symlink just a handy feature for DBAs, or is it integral to the design?

It is really just for DBAs. pgBackRest does not use it because it is not available for all repo types, e.g. CIFS. I really wonder if this is used at all in the real world. I had a specific use case for it back in the day but haven't used it in a long time. Probably somebody is somewhere, so we can't just remove it.

I'm fine with adding an option for this. In the past we have resisted making bad changes for broken immutable filesystems but this one sounds quite sensible and the goal is critically important.

I hesitate to mention this, but if you set `repo-type=cifs` then pgBackRest will not attempt to create a symlink. The bad part is that it also does not fsync any directories so it increases the chance of data loss. Still, might be useful for testing or as a stopgap.

**Comment by RonJohn2** [comment]
> How do you get data back?
Good question.  PG is so darned robust, the app  isn't buggy _that way_, and the app support people don't do stupid things very often, so they've never asked me for backups older than what's in the pgbr repos.

The immutability is hidden from the "end users": I can `rm` a file, and `ls` says it's gone.  The ExaGrid admins can still see it, though.  Thus, apparently, even if ransomware hackers get in, start doing their thing, and see that files are being encrypted, the originals are still there.

`if you set repo-type=cifs then pgBackRest will not attempt to create a symlink. The bad part is that it also does not fsync any directorie`

I wonder if fsync is relevant in this situation.  I'm definitely going to try this, though, since I trust pgbackrest a heck of a lot more than my ability to restore from base backups and giant lists of WAL files.

**Comment by dwsteele** [comment]
I have implemented this in #2674 so closing this issue.

It would be very helpful if you could test this patch in your environment to be sure there are no additional issues.

**Comment by dwsteele** [comment]
> I wonder if fsync is relevant in this situation.

It may not be, but the Posix standard requires directory fsyncs so we do them. The CIFS driver still does file fsyncs so that part is good -- if the file is there it will be fine. Of course restore will catch any missing/corrupt files but that's not the best time to be finding out.

**Comment by RonJohn2** [comment]
> I have implemented this in [#2674](https://github.com/pgbackrest/pgbackrest/pull/2674) so closing this issue.
> 
> It would be very helpful if you could test this patch in your environment to be sure there are no additional issues.

Sadly, I do not have access to a build environment.

**Comment by dwsteele** [comment]
OK, perhaps somebody else will be able to test it. The next release is months away.
