### ISSUE TITLE
No error on stderr

### ISSUE THREAD

**Issue by L30Bola** [pgbackrest/pgbackrest#289]
So, I'm trying to setup pgBackRest 1.11 with an instance of PostgreSQL 9.3. 

Both of them are running inside a Docker container, one with the PostgreSQL server and the other with pgBackRest. I'm trying to connect them and getting a very strange result. 

I've already setup SSH on both containers, with key verification and I'm successfully connecting manually between them. 

When I execute `pgbackrest --stanza=main --log-level-console=detail backup` I get this error:
```
-------------------PROCESS START-------------------
2016-12-07 10:47:08.297 P00   WARN: option retention-full is not set, the repository may run out of space
                                    HINT: to retain full backups indefinitely (without warning), set option 'retention-full' to the maximum.
2016-12-07 10:47:08.297 P00   INFO: backup start 1.11: --db-host=banco --db-path=/var/lib/pgsql/9.3/data --db-user=postgres --repo-path=/var/lib/pgbackrest --stanza=main
2016-12-07 10:47:08.308 P00   WARN: no prior backup exists, incr backup has been changed to full
2016-12-07 10:47:09.417 P00   INFO: execute exclusive pg_start_backup() with label "pgBackRest backup started at 2016-12-07 10:47:08": backup begins after the next regular checkpoint completes
2016-12-07 10:47:09.622 P00   INFO: backup start archive = 000000010000000000000008, lsn = 0/8000028
2016-12-07 10:47:09.829 P00  ERROR: [103]: remote process terminated on banco host: no error on stderr
2016-12-07 10:47:09.830 P00   INFO: backup stop

-------------------PROCESS START-------------------
2016-12-07 10:50:46.576 P00   WARN: option retention-full is not set, the repository may run out of space
                                    HINT: to retain full backups indefinitely (without warning), set option 'retention-full' to the maximum.
2016-12-07 10:50:46.576 P00   INFO: backup start 1.11: --db-host=banco --db-path=/var/lib/pgsql/9.3/data --db-user=postgres --log-level-stderr=info --repo-path=/var/lib/pgbackrest --stanza=main
2016-12-07 10:50:46.587 P00   WARN: no prior backup exists, incr backup has been changed to full
2016-12-07 10:50:47.689 P00   INFO: execute exclusive pg_start_backup() with label "pgBackRest backup started at 2016-12-07 10:50:46": backup begins after the next regular checkpoint completes
2016-12-07 10:50:47.797 P00  ERROR: [132]: raised on banco host: ERROR:  a backup is already in progress
                                           HINT:  Run pg_stop_backup() and try again.:
                                           select to_char(current_timestamp, 'YYYY-MM-DD HH24:MI:SS.US TZ'), pg_xlogfile_name(lsn), lsn::text from pg_start_backup('pgBackRest backup started at 2016-12-07 10:50:46', false) as lsn
2016-12-07 10:50:47.800 P00   INFO: backup stop
```

The second time I try to execute the backup, it says that "a backup is already in progress" which isn't true.

The `/etc/pgbackrest.conf`found inside the PostgreSQL container:
```
[main]
db-path=/var/lib/pgsql/9.3/data

[global]
backup-host=backup
backup-user=backrest
repo-path=/var/lib/pgbackrest
```

And the `/etc/pgbackrest.conf` found inside the pgBackRest container:
```
[main]
db1-host=banco
db1-path=/var/lib/pgsql/9.3/data
db1-user=postgres

[global]
repo-path=/var/lib/pgbackrest
```

I've been able to execute both of them successfully inside one container, but I'd like to split them.

**Comment by dwsteele** [comment]
It actually is in a backup mode because Postgres keeps the backup open when the calling process exits.  You can use the `stop-auto` option to enabled pgBackRest to stop it automatically or call pg_stop_backup() manually.  I would suggest the former.

None of that explains the real error, though, which is being obscured by a logging bug that has been fixed in master but not released yet.  That will be out on Tuesday so it might be best to wait until then.

It's a pretty vanilla install and I can't think of what would be erroring at that point.

**Comment by L30Bola** [comment]
Just to get you updated: I tried and got the same error with the actual master branch. It's version is 1.12dev.

**Comment by dwsteele** [comment]
Well, that sucks!  Can you run with --log-level-file=debug and send the output?

**Comment by L30Bola** [comment]
I tried again and got it through! Probably I had some misconfiguration. I'm being able to backup and restore with the 1.12dev version. I'll get this configuration, the one working with 1.12, and test it on 1.11.

**Comment by L30Bola** [comment]
Still getting the same error from before. But the good news is that the version 1.12dev is working as it should. Thanks for the help :D

**Comment by dwsteele** [comment]
You're welcome!  I thought I had only changed reporting, not behavior, but it may have been some other bug that I fixed in this release.  Let me know if it breaks when the release version comes out.

**Comment by L30Bola** [comment]
I got the error again today. Don't know what is causing it though. As you asket before, I'm posting the debug log:

Log from the PostgreSQL 9.3 Docker Container:
```
[postgres@095142a55e1d ~]$ pgbackrest --stanza=data --log-level-console=debug check
2016-12-08 20:06:40.657 P00   INFO: check command begin 1.12dev: --backup-host=backup --backup-user=backrest --db-path=/var/lib/pgsql/9.3/data/ --log-level-console=debug --repo-path=/var/lib/pgbackrest/ --stanza=data
2016-12-08 20:06:40.658 P00  DEBUG:     Protocol::Protocol::protocolGet(): iRemoteIdx = <1>, oParam = [undef], strRemoteType = backup
2016-12-08 20:06:40.658 P00  DEBUG:     Protocol::Protocol::protocolGet: create (cached) remote protocol
2016-12-08 20:06:40.658 P00  DEBUG:     Protocol::RemoteMaster->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 1830, strCommand = /usr/bin/pgbackrest --buffer-size=4194304 --command=check --compress-level=6 --compress-level-network=3 --protocol-timeout=1830 --repo-path=/var/lib/pgbackrest/ --stanza=data --type=backup remote, strCommandSSH = ssh, strHost = backup, strRemoteType = backup, strUser = backrest
2016-12-08 20:06:40.658 P00  DEBUG:     Protocol::CommonMaster->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 1830, strCommand = ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no backrest@backup '/usr/bin/pgbackrest --buffer-size=4194304 --command=check --compress-level=6 --compress-level-network=3 --protocol-timeout=1830 --repo-path=/var/lib/pgbackrest/ --stanza=data --type=backup remote', strId = backup, strName = remote, strRemoteType = backup
ERROR [107]: remote process terminated on backup host: no error on stderr
2016-12-08 20:06:40.892 P00  DEBUG:     Common::Exit::exitSafe(): iExitCode = [undef], oException = [object], strSignal = [undef]
2016-12-08 20:06:40.892 P00  DEBUG:     Protocol::Protocol::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2016-12-08 20:06:40.892 P00  DEBUG:     Protocol::Protocol::protocolDestroy=>: iExitStatus = 0
2016-12-08 20:06:40.892 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
2016-12-08 20:06:40.892 P00   INFO: check command end: aborted with exception [107]
2016-12-08 20:06:40.892 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 107
```

Log from the pgBackRest Docker container:
```
[backrest@66214a978628 ~]$ pgbackrest --stanza=data --log-level-console=debug check
2016-12-08 20:09:36.473 P00   INFO: check command begin 1.12dev: --db-host=banco --db-path=/var/lib/pgsql/9.3/data/ --db-timeout=2700 --db-user=postgres --log-level-console=debug --repo-path=/var/lib/pgbackrest/ --stanza=data
2016-12-08 20:09:36.474 P00  DEBUG:     Protocol::Protocol::protocolGet(): iRemoteIdx = <1>, oParam = [undef], strRemoteType = db
2016-12-08 20:09:36.474 P00  DEBUG:     Protocol::Protocol::protocolGet: create (cached) remote protocol
2016-12-08 20:09:36.474 P00  DEBUG:     Protocol::RemoteMaster->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 2730, strCommand = /usr/bin/pgbackrest --buffer-size=4194304 --command=check --compress-level=6 --compress-level-network=3 --db-timeout=2700 --protocol-timeout=2730 --repo-path=/var/lib/pgbackrest/ --stanza=data --type=db remote, strCommandSSH = ssh, strHost = banco, strRemoteType = db, strUser = postgres
2016-12-08 20:09:36.474 P00  DEBUG:     Protocol::CommonMaster->new(): iBufferMax = 4194304, iCompressLevel = 6, iCompressLevelNetwork = 3, iProtocolTimeout = 2730, strCommand = ssh -o LogLevel=error -o Compression=no -o PasswordAuthentication=no postgres@banco '/usr/bin/pgbackrest --buffer-size=4194304 --command=check --compress-level=6 --compress-level-network=3 --db-timeout=2700 --protocol-timeout=2730 --repo-path=/var/lib/pgbackrest/ --stanza=data --type=db remote', strId = banco, strName = remote, strRemoteType = db
2016-12-08 20:09:36.717 P00  DEBUG:     File->new(): oProtocol = [object], strBackupPath = /var/lib/pgbackrest/, strDefaultFileMode = <0640>, strDefaultPathMode = <0750>, strStanza = data
2016-12-08 20:09:36.717 P00  DEBUG:     Db->new(): iRemoteIdx = 1
2016-12-08 20:09:36.717 P00  DEBUG:     Protocol::Protocol::protocolGet(): iRemoteIdx = 1, oParam = [undef], strRemoteType = db
2016-12-08 20:09:36.717 P00  DEBUG:     Protocol::Protocol::protocolGet: found cached protocol
2016-12-08 20:09:36.717 P00  DEBUG:     Db::dbObjectGet=>: iDbMasterIdx = 1, iDbStandbyIdx = [undef], oDbMaster = [object], oDbStandby = [undef]
2016-12-08 20:09:36.717 P00  DEBUG:     Db->info(): strDbPath = </var/lib/pgsql/9.3/data/>
2016-12-08 20:09:36.718 P00  DEBUG:     File->new(): oProtocol = [object], strBackupPath = /var/lib/pgbackrest/, strDefaultFileMode = <0640>, strDefaultPathMode = <0750>, strStanza = data
2016-12-08 20:09:36.719 P00  DEBUG:     Db->info=>: iDbCatalogVersion = 201306121, iDbControlVersion = 937, strDbVersion = 9.3, ullDbSysId = 6361853740983508215
2016-12-08 20:09:36.719 P00  DEBUG:     Db->executeSqlRow(): strSql = select (regexp_matches(split_part(version(), ' ', 2), '^[0-9]+.[0-9]+'))[1], setting from pg_settings where name = 'data_directory'
2016-12-08 20:09:36.719 P00  DEBUG:     Db::executeSql(): bIgnoreError = <false>, bResult = <true>, strSql = select (regexp_matches(split_part(version(), ' ', 2), '^[0-9]+.[0-9]+'))[1], setting from pg_settings where name = 'data_directory'
2016-12-08 20:09:36.931 P00  DEBUG:     Db::executeSql=>: stryResult = ((9.3, /var/lib/pgsql/9.3/data))
2016-12-08 20:09:36.931 P00  DEBUG:     Db->executeSqlRow=>: stryResult = (9.3, /var/lib/pgsql/9.3/data)
2016-12-08 20:09:36.931 P00  DEBUG:     DbVersion->versionSupport=>: strySupportVersion = (8.3, 8.4, 9.0, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6)
2016-12-08 20:09:36.932 P00  DEBUG:     Db->versionGet=>: strDbPath = /var/lib/pgsql/9.3/data, strDbVersion = 9.3
2016-12-08 20:09:36.932 P00  DEBUG:     Db->executeSqlOne(): strSql = select pg_is_in_recovery()
2016-12-08 20:09:36.932 P00  DEBUG:     Db::executeSql(): bIgnoreError = <false>, bResult = <true>, strSql = select pg_is_in_recovery()
2016-12-08 20:09:37.038 P00  DEBUG:     Db::executeSql=>: stryResult = ((0))
2016-12-08 20:09:37.038 P00  DEBUG:     Db->executeSqlOne=>: strResult = 0
2016-12-08 20:09:37.039 P00  DEBUG:     Db->isStandby=>: bStandby = false
2016-12-08 20:09:37.039 P00  DEBUG:     Db->executeSqlOne(): strSql = show archive_mode
2016-12-08 20:09:37.039 P00  DEBUG:     Db::executeSql(): bIgnoreError = <false>, bResult = <true>, strSql = show archive_mode
2016-12-08 20:09:37.144 P00  DEBUG:     Db::executeSql=>: stryResult = ((on))
2016-12-08 20:09:37.145 P00  DEBUG:     Db->executeSqlOne=>: strResult = on
2016-12-08 20:09:37.145 P00  DEBUG:     Db->executeSqlOne(): strSql = show archive_command
2016-12-08 20:09:37.145 P00  DEBUG:     Db::executeSql(): bIgnoreError = <false>, bResult = <true>, strSql = show archive_command
2016-12-08 20:09:37.251 P00  DEBUG:     Db::executeSql=>: stryResult = ((pgbackrest --stanza=data archive-push %p))
2016-12-08 20:09:37.251 P00  DEBUG:     Db->executeSqlOne=>: strResult = pgbackrest --stanza=data archive-push %p
2016-12-08 20:09:37.252 P00  DEBUG:     Db::executeSql(): bIgnoreError = <false>, bResult = <true>, strSql = select pg_create_restore_point('pgBackRest Archive Check');
2016-12-08 20:09:37.359 P00  DEBUG:     Db::executeSql=>: stryResult = ((0/1784710))
2016-12-08 20:09:37.359 P00  DEBUG:     Db->executeSqlOne(): strSql = select pg_xlogfile_name from pg_xlogfile_name(pg_switch_xlog());
2016-12-08 20:09:37.359 P00  DEBUG:     Db::executeSql(): bIgnoreError = <false>, bResult = <true>, strSql = select pg_xlogfile_name from pg_xlogfile_name(pg_switch_xlog());
2016-12-08 20:09:37.464 P00  DEBUG:     Db::executeSql=>: stryResult = ((000000010000000000000001))
2016-12-08 20:09:37.464 P00  DEBUG:     Db->executeSqlOne=>: strResult = 000000010000000000000001
2016-12-08 20:09:37.464 P00   INFO: switch xlog 000000010000000000000001
2016-12-08 20:09:37.464 P00  DEBUG:     Db->xlogSwitch=>: strXlogFileName = 000000010000000000000001
ERROR [130]: archive.info does not exist but is required to get WAL segments
HINT: is archive_command configured in postgresql.conf?
HINT: use --no-archive-check to disable archive checks during backup if you have an alternate archiving scheme.
^C2016-12-08 20:11:54.489 P00  DEBUG:     Protocol::Protocol::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2016-12-08 20:11:54.490 P00  DEBUG:     Protocol::Protocol::protocolDestroy: found cached protocol: iRemoteIdx = 1, strRemoteType = db
ERROR [124]: remote process terminated on banco host (exit status 255): Killed by signal 2.
WARN: unable to shutdown protocol [124]: remote process terminated on banco host (exit status 255): Killed by signal 2.
2016-12-08 20:11:54.498 P00  DEBUG:     Protocol::CommonMaster->close=>: iExitStatus = 124
2016-12-08 20:11:54.499 P00  DEBUG:     Protocol::Protocol::protocolDestroy=>: iExitStatus = 124
2016-12-08 20:11:54.499 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
ERROR [138]: terminated on signal [SIGINT]
2016-12-08 20:11:54.501 P00   INFO: check command end: terminated on signal [SIGINT]
2016-12-08 20:11:54.501 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 138
```
On this container, this ERROR[130] keeps getting spammed forever on the console.

Let me know if you need any other log.

**Comment by dwsteele** [comment]
You must have changed you config files since last time - you are using stanza=data instead of stanza=main.  Can you post the config files again?  Error 107 is a config error.

**Comment by L30Bola** [comment]
Yeah I changed them just to match the folder name inside PostgreSQL folder with the stanza name.

Here goes the config form both the pgbackrest.conf inside those containers and the postgresql.conf from the database host:

Backup Container `pgbackrest.conf`:
```
[data]
db1-host=banco2
db1-path=/var/lib/pgsql/9.3/data
db1-user=postgres
retention-archive=7
retention-archive-type=incr
db-timeout=2700

[global]
repo-path=/var/lib/pgbackrest
stop-auto=y
```

Database Container `pgbackrest.conf`:
```
[data]
db-path=/var/lib/pgsql/9.3/data

[global]
stop-auto=y
backup-host=backup2
backup-user=backrest
repo-path=/var/lib/pgbackrest
```

Database Container `postgresql.conf`:
```
wal_level = archive
archive_mode = on
archive_command = 'pgbackrest --stanza=data archive-push %p'
archive_timeout = 600
```
Of couse some configs inside `postgresql.conf` so ithis gets smaller.

**Comment by dwsteele** [comment]
OK, the first thing I would try is to remove the `db-timeout` option from your config.  It could be a bad interaction with `protocol-timeout` even though `protocol-timeout` should be automatically set higher than `db-timeout`.

Unless you are running a very large database the default `db-timeout` tends to be sufficient.  In any case, we can see if that's the issue.

I would also set `start-fast=y` to reduce possible timeout issues.

**Comment by dwsteele** [comment]
Any luck on this?

**Comment by L30Bola** [comment]
I had little time to try this. Going through it now. I'll update here ASAP

**Comment by dwsteele** [comment]
No worries, just wanted to make sure you were up and running if you needed to be.

**Comment by L30Bola** [comment]
Well, I pulled the last updates and tried it again. Here is my configs:

Backup Container `pgbackrest.conf`:
```
[data]
db1-host=banco
db1-path=/var/lib/pgsql/9.3/data
db1-user=postgres
retention-archive=7
retention-archive-type=incr

[global]
repo-path=/var/lib/pgbackrest
start-fast=y
stop-auto=y
```

Database Container `pgbackrest.conf`:
```
[data]
db-path=/var/lib/pgsql/9.3/data

[global]
stop-auto=y
start-fast=y
backup-host=backup
backup-user=backrest
repo-path=/var/lib/pgbackrest
```

Database Container `postgresql.conf`:
```
wal_level = hot_standby
archive_mode = on
archive_timeout = 600
max_wal_senders = 3
hot_standby = on
```

I tried a bunch of time this time (so I don't make you closes this in vain) and know I can say it's fully working. I'll let you know if I ever face another problem :D

Thanks once again for the support

**Comment by dwsteele** [comment]
OK, good to hear.  I wish we could have seen the root problem but I think it must have to do with the interaction between `db-timeout` and `protocol-timeout`.  I'll have a look at that.

**Comment by L30Bola** [comment]
Now I'm facing another problem: 

When I try to restore the backup, I get the following error:
```
[backrest@05d37b5492aa ~]$ pgbackrest --stanza=data --log-level-console=detail --delta restore
2016-12-14 18:11:14.353 P00   INFO: restore command begin 1.13dev: --db-path=/var/lib/pgsql/9.3/data --delta --log-level-console=detail --repo-path=/var/lib/pgbackrest --stanza=data
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/var/lib/pgsql/9.3/data' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
ERROR [117]: unable to open /var/lib/pgsql/9.3/data/backup.info.pgbackrest.tmp: Permission denied
2016-12-14 18:11:14.365 P00   INFO: restore command end: aborted with exception [117]
```
Now, I don't know if pgBackRest is trying to find this file on my Backup Container or in the Database Container. It doesn't make sense if it's trying to find it on the backup, since that directory doesn't even exist, since it doesn't host the Database. In either cases, this file doesn't exist on neither of the Containers.

**Comment by dwsteele** [comment]
You must be the `postgres` user when restoring since only the `postgres` user has permissions on the data directory.  The `backrest` user is for the backup server only.

**Comment by L30Bola** [comment]
Both users are on the same UID and GUID so this was prevented :D. 

Should I create a `postgres` on the Backup Container? 
And should I create a `backrest` user on the Database Container aswell?

**Comment by dwsteele** [comment]
You should not have a `backrest` user on your database host, only on the backup host.

**Comment by L30Bola** [comment]
> You should not have a `backrest`  user on your database host, only on the backup host.

Yeah that's what is happening now: I don't have that user inside my Database Container.

I have two users on the Backup Container: `backrest` and `root`.

And on the Database Container I also have two users: `postgres` and `root`.

On both containers, the user who's going to operate (don't know if it's written this way) the main process (pgbackrest is set to be executed by the user `backrest` and the PostgreSQL server is set to be executed by user `postgres`) is both with `UID` and `GUID` 5000, so I shouldn't have any permission issues between files.

My problem is restoring the backup. I was able to make the initial and the sequential daily incremental backups. But whenever I try to restore it, I get the error from [here](https://github.com/pgbackrest/pgbackrest/issues/289#issuecomment-267152916).

Also, as I said [here](https://github.com/pgbackrest/pgbackrest/issues/289#issuecomment-267022690), the user accessing the Database is `postgres` and the user maintaining the backup is `backrest`.

**Comment by sfrost** [comment]
Try just doing a simple 'touch' on the file that pgbackrest reported from a shell.  If that fails, then there is nothing different we are going to be able to do with pgbackrest to address this issue and it's a problem with your virtualization, or docker, or something else outside of pgbackrest.

Thanks!

**Comment by dwsteele** [comment]
The directory to restore to, i.e. /var/lib/pgsql/9.3/data must exist in advance.  The open error is not a file that pgBackRest is trying to find, it's trying to copy it to start the restore.  Make sure the directory exists with the correct permissions and see what happens.

If that works I'll check the code to see if perhaps the missing directory checks got push below this copy.

**Comment by dwsteele** [comment]
I take that back, I can see the check for $PGDATA is before the copy starts.  Seems like some kind of permissions issue, so best to follow Stephen's advice.

BTW - I use Docker for regression tests and I've found that CentOS can be a bit flaky when it comes to permissions.  Sometimes directories that were created by default need to be dropped and recreated to get them working correctly.

**Comment by L30Bola** [comment]
It was really a permission issue on that directory. I created it on the Backup Container and gave it his permissions (`chmod 700`, `chown backrest:backrest`). On the Database Container I created `/var/lib/pgbackrest`and gave it almost the same permissions (`chmod 700', `chown postgres:postgres`). I created it just to setup an almost the same directory structure on both Containers. 

I'm still with problems to restore it but I think it's some kind of permission issue on my Database Container side.

After all this, I stopped the PostgreSQL service, deleted the content inside my /var/lib/pgsql/9.3/data and went to try the restore. It failed with this error: 
```
[backrest@c2976556989d pgbackrest]$ pgbackrest --stanza=data --log-level-console=detail restore
2016-12-16 15:42:35.970 P00   INFO: restore command begin 1.13dev: --db-path=/var/lib/pgsql/9.3/data --log-level-console=detail --repo-path=/var/lib/pgbackrest --stanza=data
2016-12-16 15:42:35.990 P00   INFO: restore backup set 20161216-153502F
2016-12-16 15:42:36.166 P00 DETAIL: check /var/lib/pgsql/9.3/data exists
ERROR [115]: cannot restore to path '/var/lib/pgsql/9.3/data' that contains files - try using --delta if this is what you intended
2016-12-16 15:42:36.168 P00   INFO: restore command end: aborted with exception [115]

[backrest@c2976556989d pgbackrest]$ pgbackrest --stanza=data --log-level-console=detail --delta restore
2016-12-16 15:39:31.907 P00   INFO: restore command begin 1.13dev: --db-path=/var/lib/pgsql/9.3/data --delta --log-level-console=detail --repo-path=/var/lib/pgbackrest --stanza=data
WARN: --delta or --force specified but unable to find 'PG_VERSION' or 'backup.manifest' in '/var/lib/pgsql/9.3/data' to confirm that this is a valid $PGDATA directory.  --delta and --force have been disabled and if any files exist in the destination directories the restore will be aborted.
2016-12-16 15:39:31.927 P00   INFO: restore backup set 20161216-153502F
2016-12-16 15:39:32.098 P00 DETAIL: check /var/lib/pgsql/9.3/data exists
ERROR [198]: process terminated due to an unhandled exception:
Use of uninitialized value $iUserId in chown at /usr/share/perl5/pgBackRest/File.pm line 965.
 at /usr/bin/pgbackrest line 15.
        main::__ANON__('Use of uninitialized value $iUserId in chown at /usr/share/pe...') called at /usr/share/perl5/pgBackRest/File.pm line 965
        pgBackRest::File::owner(undef, 'db:absolute', '/var/lib/pgsql/9.3/data/base', 'postgres', 'postgres') called at /usr/share/perl5/pgBackRest/Restore.pm line 870
        pgBackRest::Restore::build(undef, 'pgBackRest::Manifest=HASH(0x2c8c058)') called at /usr/share/perl5/pgBackRest/Restore.pm line 1103
        pgBackRest::Restore::process('pgBackRest::Restore=HASH(0x2b868b0)') called at /usr/bin/pgbackrest line 213
        eval {...} called at /usr/bin/pgbackrest line 266

2016-12-16 15:39:32.102 P00   INFO: restore command end: aborted with exception [198]
```

So I went to try and delete the directory `/var/lib/pgsql/9.3/data` and I got this error:
```
[postgres@4aa91972df4a 9.3]$ rm -rf /var/lib/pgsql/9.3/data/
rm: cannot remove '/var/lib/pgsql/9.3/data/': Device or resource busy
[root@4aa91972df4a 9.3]# rm -rf /var/lib/pgsql/9.3/data/
rm: cannot remove '/var/lib/pgsql/9.3/data/': Device or resource busy
```

I'm investigating. I'll report ASAP I find a solution.

Thanks once again for the support

**Comment by sfrost** [comment]
The 'Use of uninitialized value $iUserId' certainly looks like a pgbackrest bug, thanks!

I agree that there's clearly an underlying issue with docker there though, which you'll need to fix before pgbackrest will work, but we should be able to fix the uninitialized value error.

Thanks again!

**Comment by dwsteele** [comment]
Yeah, this is definitely aa bug:
`Use of uninitialized value $iUserId in chown at /usr/share/perl5/pgBackRest/File.pm line 965`

If you run the restore with `--log-level-console=debug` we can see what user it's trying to use in the `chown`.  pgBackRest should be mapping users that exist in the backup but not on the restore host to something safe (the owner of $PGDATA) but something is clearly going wrong with that.

Either there is a bug (beyond the issue above), or the owner of $PGDATA is not a valid user.

**Comment by L30Bola** [comment]
Here it goes the output of the command above with `--log-level-console=debug`:

```
[backrest@e78939e8c424 pgbackrest]$ pgbackrest --stanza=data --log-level-console=debug --delta restore
2016-12-16 17:57:07.387 P00   INFO: restore command begin 1.13dev: --db-path=/var/lib/pgsql/9.3/data --delta --log-level-console=debug --repo-path=/var/lib/pgbackrest --stanza=data
2016-12-16 17:57:07.387 P00  DEBUG:     Common::Lock::lockAcquire(): bFailOnNoLock = <true>, bRemote = <false>, iProcessIdx = [undef], strLockType = restore
2016-12-16 17:57:07.387 P00  DEBUG:     Common::Lock::lockAcquire=>: bResult = true
2016-12-16 17:57:07.398 P00  DEBUG:     Protocol::Protocol::protocolGet(): iRemoteIdx = <1>, oParam = [undef], strRemoteType = backup
2016-12-16 17:57:07.398 P00  DEBUG:     Protocol::Protocol::protocolGet: create local protocol
2016-12-16 17:57:07.398 P00  DEBUG:     File->new(): oProtocol = [object], strBackupPath = /var/lib/pgbackrest, strDefaultFileMode = <0640>, strDefaultPathMode = <0750>, strStanza = data
2016-12-16 17:57:07.398 P00  DEBUG:     File->exists(): strPath = /var/lib/pgsql/9.3/data/postmaster.pid, strPathType = db:absolute
2016-12-16 17:57:07.398 P00  DEBUG:     File->exists=>: bExists = false
2016-12-16 17:57:07.399 P00  DEBUG:     File->exists(): strPath = /var/lib/pgsql/9.3/data/PG_VERSION, strPathType = db:absolute
2016-12-16 17:57:07.399 P00  DEBUG:     File->exists=>: bExists = false
2016-12-16 17:57:07.399 P00  DEBUG:     File->exists(): strPath = /var/lib/pgsql/9.3/data/backup.manifest, strPathType = db:absolute
2016-12-16 17:57:07.399 P00  DEBUG:     File->exists=>: bExists = true
2016-12-16 17:57:07.399 P00  DEBUG:     File->copy(): bAppendChecksum = <false>, bDestinationCompress = <false>, bDestinationPathCreate = <false>, bIgnoreMissingSource = <false>, bPathSync = <false>, bSourceCompressed = <false>, lModificationTime = [undef], strDestinationFile = /var/lib/pgsql/9.3/data/backup.info, strDestinationPathType = db:absolute, strExtraFunction = [undef], strGroup = [undef], strMode = <0640>, strSourceFile = backup.info, strSourcePathType = backup:cluster, strUser = [undef]
2016-12-16 17:57:07.485 P00  DEBUG:     BackupInfo->new(): bValidate = false, strBackupClusterPath = /var/lib/pgsql/9.3/data
2016-12-16 17:57:07.493 P00  DEBUG:     File->remove(): bIgnoreMissing = false, bPathSync = true, bTemp = [undef], strPath = /var/lib/pgsql/9.3/data/backup.info, strPathType = db:absolute
2016-12-16 17:57:07.498 P00  DEBUG:     File->remove=>: bRemoved = true
2016-12-16 17:57:07.499 P00  DEBUG:     BackupInfo->last(): strType = incr
2016-12-16 17:57:07.500 P00  DEBUG:     BackupCommon::backupRegExpGet(): bAnchor = <true>, bDifferential = true, bFull = true, bIncremental = true
2016-12-16 17:57:07.500 P00  DEBUG:     BackupCommon::backupRegExpGet=>: strRegExp = ^[0-9]{8}\-[0-9]{6}F(\_[0-9]{8}\-[0-9]{6}(D|I)){0,1}$
2016-12-16 17:57:07.501 P00  DEBUG:     BackupInfo->list(): strFilter = ^[0-9]{8}\-[0-9]{6}F(\_[0-9]{8}\-[0-9]{6}(D|I)){0,1}$, strOrder = reverse
2016-12-16 17:57:07.501 P00  DEBUG:     BackupInfo->list=>: stryBackup = (20161216-174454F)
2016-12-16 17:57:07.502 P00  DEBUG:     BackupInfo->last=>: strBackup = 20161216-174454F
2016-12-16 17:57:07.502 P00   INFO: restore backup set 20161216-174454F
2016-12-16 17:57:07.502 P00  DEBUG:     File->exists(): strPath = 20161216-174454F, strPathType = backup:cluster
2016-12-16 17:57:07.504 P00  DEBUG:     File->exists=>: bExists = true
2016-12-16 17:57:07.505 P00  DEBUG:     File->copy(): bAppendChecksum = <false>, bDestinationCompress = <false>, bDestinationPathCreate = <false>, bIgnoreMissingSource = <false>, bPathSync = <false>, bSourceCompressed = <false>, lModificationTime = [undef], strDestinationFile = /var/lib/pgsql/9.3/data/backup.manifest, strDestinationPathType = db:absolute, strExtraFunction = [undef], strGroup = [undef], strMode = <0640>, strSourceFile = 20161216-174454F/backup.manifest, strSourcePathType = backup:cluster, strUser = [undef]
2016-12-16 17:57:07.645 P00  DEBUG:     Restore->manifestOwnershipCheck(): oManifest = [object]
2016-12-16 17:57:07.716 P00  DEBUG:     File->remove(): bIgnoreMissing = true, bPathSync = <false>, bTemp = true, strPath = /var/lib/pgsql/9.3/data/global/pg_control, strPathType = db:absolute
2016-12-16 17:57:07.716 P00  DEBUG:     File->remove=>: bRemoved = false
2016-12-16 17:57:07.716 P00  DEBUG:     Restore->clean(): oManifest = [object]
2016-12-16 17:57:07.716 P00 DETAIL: check /var/lib/pgsql/9.3/data exists
2016-12-16 17:57:07.716 P00  DEBUG:     File->exists(): strPath = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.716 P00  DEBUG:     File->exists=>: bExists = true
2016-12-16 17:57:07.716 P00  DEBUG:     File->manifest(): strPath = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.716 P00  DEBUG:     File->manifestRecurse(): iDepth = 0, oManifestHashRef = [hash], strPathFileOp = [undef], strPathOp = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.717 P00  DEBUG:     File->manifestRecurse(): iDepth = 1, oManifestHashRef = [hash], strPathFileOp = base, strPathOp = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.717 P00   INFO: remove invalid files/paths/links from /var/lib/pgsql/9.3/data
2016-12-16 17:57:07.717 P00  DEBUG:     File->exists(): strPath = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.717 P00  DEBUG:     File->exists=>: bExists = true
2016-12-16 17:57:07.717 P00  DEBUG:     File->manifest(): strPath = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.718 P00  DEBUG:     File->manifestRecurse(): iDepth = 0, oManifestHashRef = [hash], strPathFileOp = [undef], strPathOp = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.718 P00  DEBUG:     File->manifestRecurse(): iDepth = 1, oManifestHashRef = [hash], strPathFileOp = base, strPathOp = /var/lib/pgsql/9.3/data, strPathType = db:absolute
2016-12-16 17:57:07.718 P00 DETAIL: set ownership postgres:postgres on /var/lib/pgsql/9.3/data/base
2016-12-16 17:57:07.718 P00  DEBUG:     File->owner(): strFile = /var/lib/pgsql/9.3/data/base, strGroup = postgres, strPathType = db:absolute, strUser = postgres
2016-12-16 17:57:07.719 P00  DEBUG:     Common::Exit::exitSafe(): iExitCode = [undef], oException = Use of uninitialized value $iUserId in chown at /usr/share/perl5/pgBackRest/File.pm line 965.
                                         at /usr/bin/pgbackrest line 15.
                                        	main::__ANON__('Use of uninitialized value $iUserId in chown at /usr/share/pe...') called at /usr/share/perl5/pgBackRest/File.pm line 965
                                        	pgBackRest::File::owner(undef, 'db:absolute', '/var/lib/pgsql/9.3/data/base', 'postgres', 'postgres') called at /usr/share/perl5/pgBackRest/Restore.pm line 653
                                        	pgBackRest::Restore::clean(undef, 'pgBackRest::Manifest=HASH(0x1b98098)') called at /usr/share/perl5/pgBackRest/Restore.pm line 1100
                                        	pgBackRest::Restore::process('pgBackRest::Restore=HASH(0x1a92740)') called at /usr/bin/pgbackrest line 213
                                        	eval {...} called at /usr/bin/pgbackrest line 266
                                        , strSignal = [undef]
2016-12-16 17:57:07.719 P00  DEBUG:     Protocol::Protocol::protocolDestroy(): bComplete = false, iRemoteIdx = [undef], strRemoteType = [undef]
2016-12-16 17:57:07.719 P00  DEBUG:     Protocol::Protocol::protocolDestroy=>: iExitStatus = 0
2016-12-16 17:57:07.719 P00  DEBUG:     Common::Lock::lockRelease(): bFailOnNoLock = false
ERROR [198]: process terminated due to an unhandled exception:
Use of uninitialized value $iUserId in chown at /usr/share/perl5/pgBackRest/File.pm line 965.
 at /usr/bin/pgbackrest line 15.
	main::__ANON__('Use of uninitialized value $iUserId in chown at /usr/share/pe...') called at /usr/share/perl5/pgBackRest/File.pm line 965
	pgBackRest::File::owner(undef, 'db:absolute', '/var/lib/pgsql/9.3/data/base', 'postgres', 'postgres') called at /usr/share/perl5/pgBackRest/Restore.pm line 653
	pgBackRest::Restore::clean(undef, 'pgBackRest::Manifest=HASH(0x1b98098)') called at /usr/share/perl5/pgBackRest/Restore.pm line 1100
	pgBackRest::Restore::process('pgBackRest::Restore=HASH(0x1a92740)') called at /usr/bin/pgbackrest line 213
	eval {...} called at /usr/bin/pgbackrest line 266

2016-12-16 17:57:07.719 P00   INFO: restore command end: aborted with exception [198]
2016-12-16 17:57:07.719 P00  DEBUG:     Common::Exit::exitSafe=>: iExitCode = 198
```

Anything else, just ask :D

**Comment by dwsteele** [comment]
So this says the `postgres` user does not exist on the host you are restoring to.  Is that true?

What do you get from `ls -lah /var/lib/pgsql/9.3`?

**Comment by L30Bola** [comment]
No, it does exists. Here are some outputs from both Containers:

Backup Container:
```bash
[root@81681a31836e pgbackrest]# id backrest
uid=5000(backrest) gid=5000(backrest) groups=5000(backrest)
[root@81681a31836e pgbackrest]# id postgres
id: postgres: no such user
[root@81681a31836e pgbackrest]# ls -lah /var/lib/pgsql/9.3
total 4.0K
drwx------. 3 backrest backrest   18 Dec 16 17:22 .
drwx------. 4 backrest backrest   31 Dec 16 18:06 ..
drwx------. 2 backrest backrest 4.0K Dec 16 18:06 data
```

Database Container:
```bash
[root@7f75b1d0cfb0 9.3]# id postgres
uid=5000(postgres) gid=5000(postgres) groups=5000(postgres)
[root@7f75b1d0cfb0 9.3]# id backrest
id: backrest: no such user
[root@7f75b1d0cfb0 9.3]# ls -lah /var/lib/pgsql/9.3
total 4.0K
drwx------. 4 postgres postgres   33 Dec 14 09:07 .
drwx------. 4 postgres postgres   52 Dec 14 09:07 ..
drwx------. 2 postgres postgres 4.0K Dec 16 18:06 data
```

**Comment by dwsteele** [comment]
Well, the the pgBackRest code it is not able to resolve `postgres` to a uid.  The fact that it is blowing up on an undefined UID is a minor bug, but it has nothing to do with why it can't be resolved in the first place.

As I've said before, my experience is that ownership/permissions are very flaky in CentOS Docker containers.  At the moment I don't have any ideas.

**Comment by L30Bola** [comment]
As soon as I have time i'll rebuild both on Debian/Ubuntu containers and report back. Should I try them on VMs too?

**Comment by dwsteele** [comment]
It might be best to start with VMs and then go back to Docker if that works OK.

**Comment by L30Bola** [comment]
As I said before I don't have much time to test it, so I'm staying on Docker. 

Made some tests now and I got this error, which is similar with the one I got friday:
```
[backrest@9feb0206f334 ~]$ pgbackrest --stanza=data --log-level-console=detail --delta restore
2016-12-19 08:34:01.664 P00   INFO: restore command begin 1.13dev: --db-path=/var/lib/pgsql/9.3/data --delta --log-level-console=detail --repo-path=/var/lib/pgbackrest --stanza=data
2016-12-19 08:34:01.694 P00   INFO: restore backup set 20161219-082523F_20161219-082647I
2016-12-19 08:34:01.923 P00 DETAIL: check /var/lib/pgsql/9.3/data exists
2016-12-19 08:34:01.924 P00   INFO: remove invalid files/paths/links from /var/lib/pgsql/9.3/data
2016-12-19 08:34:01.925 P00 DETAIL: set ownership postgres:postgres on /var/lib/pgsql/9.3/data/base
ERROR [198]: process terminated due to an unhandled exception:
Use of uninitialized value $iUserId in chown at /usr/share/perl5/pgBackRest/File.pm line 965.
 at /usr/bin/pgbackrest line 15.
        main::__ANON__('Use of uninitialized value $iUserId in chown at /usr/share/pe...') called at /usr/share/perl5/pgBackRest/File.pm line 965
        pgBackRest::File::owner(undef, 'db:absolute', '/var/lib/pgsql/9.3/data/base', 'postgres', 'postgres') called at /usr/share/perl5/pgBackRest/Restore.pm line 653
        pgBackRest::Restore::clean(undef, 'pgBackRest::Manifest=HASH(0x245a110)') called at /usr/share/perl5/pgBackRest/Restore.pm line 1100
        pgBackRest::Restore::process('pgBackRest::Restore=HASH(0x1f30c88)') called at /usr/bin/pgbackrest line 213
        eval {...} called at /usr/bin/pgbackrest line 266

2016-12-19 08:34:01.927 P00   INFO: restore command end: aborted with exception [198]
```

On line 6: **set ownership postgres:postgres on /var/lib/pgsql/9.3/data/base**. 

Seeing this I changed all my user inside the Backup Container from backrest to postgres. Now I'm being able to backup and restore. 

Now, after trying to restore and restoring it successfully, I noticed it restored the dump inside the Backup Container. Was it made to do this? I missed some config?

**Comment by dwsteele** [comment]
The restore command will always restore to the host where it is run.  This likely explains the issues you've been having.

**Comment by L30Bola** [comment]
Then the only problem now is that when I try to restore the backup, it always tries with the `postgres` user. Other than that, I THINK it's working.

**Comment by dwsteele** [comment]
It tries to restore as the postgres user because you backed up as the postgres user.  It should override that with the owner of the $PGDATA directory if the postgres user does not exist.

**Comment by L30Bola** [comment]
Dump question: Does it tries to find $PGDATA owner, expanding it? Because I've tried echoing the ENV and it doesn't exist.

**Comment by dwsteele** [comment]
By $PGDATA I mean whatever is defined as `db-path`.  The owner of that directory is the one it will use as the default if the original user does not exist.

**Comment by dwsteele** [comment]
I'm preparing a fix for the `Use of uninitialized value $iUserId in chown` issue.

How would you like your name to appear in the release notes.  Is "Leonardo G G Avellar" OK?

**Comment by L30Bola** [comment]
Whoa! I wasn't expecting this, but yeah, it could be my name (Leonardo G G Avellar, or even just Leonardo Avellar) or my nickname, which I use for everything: L30Bola.

**Comment by dwsteele** [comment]
I like to give credit where it is due.  Committed at 39744a4f1dbbe4e593bebaa37a6be93dae0da214.
