### ISSUE TITLE
intermittent 15 minute slowdown in S3 uploads after system update

### ISSUE THREAD

**Issue by slava-pagerduty** [pgbackrest/pgbackrest#940]
Please provide the following information when submitting an issue (feature requests or general comments can skip this):

1. pgBackRest version:
2.23
2. PostgreSQL version:
11.6

3. Operating system/version - if you have more than one server (for example, a database server, a repository host server, one or more standbys), please specify each:
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-1058-aws x86_64) running on AWS i3.8xlarge (32 CPU 256GB RAM)

4. Did you install pgBackRest from source or from a package?
package

5. Please attach the following as applicable:
    - `pgbackrest.conf` file(s)
[global]
process-max=12
start-fast=y
archive-async=y
spool-path=/var/spool/pgbackrest
repo1-type=s3
repo1-path=/pgbackrest-repo
repo1-retention-full=8
repo1-retention-diff=20
repo1-s3-endpoint=s3.amazonaws.com
repo1-s3-region=us-west-2
repo1-s3-bucket=pd-pg-warehouse
repo1-s3-key=A****************
repo1-s3-key-secret=O**********************
[pg-warehouse]
db-path=/data/pg-warehouse/

    - `postgresql.conf` settings applicable to pgBackRest (`archive_command`, `archive_mode`, `listen_addresses`, `max_wal_senders`, `wal_level`, `port`)
(no problems here)
    - errors in the postgresql log file before or during the time you experienced the issue
(no errors here)
    - log file in `/var/log/pgbackrest` for the commands run (e.g. `/var/log/pgbackrest/mystanza_backup.log`)
see below for a portion of log with relevant information

7. Describe the issue:
probably this is similar to previously reported issue: https://github.com/pgbackrest/pgbackrest/issues/788

After installing update on 2020-02-05 we are seeing intermittent slowdowns in S3 transfer.
Backup transfer would run for few minutes and then sit for approximately 15 minutes after which I see the following messages:
```
common/io/http/client::httpClientRequest: retry KernelError: tls failed syscall: [110] Connection timed out
storage/s3/storage::storageS3Request: retry RequestTimeTooSkewed: The difference between the request time and the current time is too large.
```
 
Here are the log records around such slowdown.
```
2020-02-14 21:52:26.464 P00  DEBUG:     storage/storage::storageNewWrite: (this: {type: s3, path: {"/pgbackrest-repo"}, write: true}, fileExp: {"<REPO:BACKUP>/20200209-110003F_20200214-214800D/backup.manifest.copy"}, param.modeFile: 0000, param.modePath: 0000, param.user: null, param.group: null, param.timeModified: 0, param.noCreatePath: false, param.noSyncFile: false, param.noSyncPath: false, param.noAtomic: false, param.compressible: false)
2020-02-14 21:52:26.464 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: (this: {StorageS3}, file: {"/pgbackrest-repo/backup/pg-warehouse/20200209-110003F_20200214-214800D/backup.manifest.copy"})
2020-02-14 21:52:26.464 P00  DEBUG:     storage/s3/storage::storageS3NewWrite: => {type: s3, name: {"/pgbackrest-repo/backup/pg-warehouse/20200209-110003F_20200214-214800D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
2020-02-14 21:52:26.464 P00  DEBUG:     storage/storage::storageNewWrite: => {type: s3, name: {"/pgbackrest-repo/backup/pg-warehouse/20200209-110003F_20200214-214800D/backup.manifest.copy"}, modeFile: 0000, modePath: 0000, createPath: true, syncFile: true, syncPath: true, atomic: true}
2020-02-14 21:52:26.464 P00  DEBUG:     info/manifest::manifestSave: (this: {Manifest}, write: {IoWrite})
2020-02-14 21:52:26.473 P00  DEBUG:     info/info::infoSave: (this: {Info}, write: {IoWrite}, callbackFunction: (function *), callbackData: *void)
2020-02-14 22:08:07.016 P00  DEBUG:     common/io/http/client::httpClientRequest: retry KernelError: tls failed syscall: [110] Connection timed out
2020-02-14 22:08:07.069 P00  DEBUG:     storage/s3/storage::storageS3Request: retry RequestTimeTooSkewed: The difference between the request time and the current time is too large.
2020-02-14 22:08:07.297 P00  DEBUG:     info/info::infoSave: => void
2020-02-14 22:08:07.297 P00  DEBUG:     info/manifest::manifestSave: => void
2020-02-14 22:08:07.297 P00  DEBUG:     command/backup/backup::backupManifestSaveCopy: => void
2020-02-14 22:08:07.298 P00  DEBUG:     command/backup/backup::backupJobResult: (manifest: {Manifest}, host: null, fileName: {"/data/pg-warehouse/base/16401/677988007.4"}, fileRemove: {[]}, job: {state: done, key: {"pg_data/base/16401/677988007.4"}, command: {command: backupFile}, code: 0, message: null, result: {VariantList}}, sizeTotal: 1604360011819, sizeCopied: 64736969131, pageSize: 8192)
```

I can attach whole log file, but essentially the slowdown cases look exactly the same.

I have read through the related issues:
https://github.com/pgbackrest/pgbackrest/issues/707 
https://github.com/pgbackrest/pgbackrest/issues/788 
There seems to be issues related to kernel updates. I am attaching the update log after which the slowdown started to happen (everything was running smoothly for months before the update)
[ubuntu_updates_20200204.txt]
(https://github.com/pgbackrest/pgbackrest/files/4221931/ubuntu_updates_20200204.txt)

I have opened a ticket with AWS support, so will update here once I have more information.
But would be great to know if anyone else experience similar issues or there are any solutions.

**Comment by dwsteele** [comment]
We never got to the root of this problem, other than that it seems to be a kernel/driver problem in some cases, at least.  The retry it not ideal but at least it allows the backup to complete.

Please let us know if AWS support has anything to say about this issue.

**Comment by slava-pagerduty** [comment]
Thanks for replying. I am following with AWS and hope they have someone on networking side to look into this. On pgbackrest side is it possible to control how many threads run S3 transfer or lower the timeout interval?

**Comment by dwsteele** [comment]
`process-max` controls how many threads (processes, really) do S3 transfer.

The timeout is tricky here because we are blocked inside a write() call when this happens.  We could use a timer signal, perhaps, but at that point our state is going to be a bit dodgy and we'd probably have to exit.

**Comment by slava-pagerduty** [comment]
I don't have much update here and AWS support wasn't very helpful in troubleshooting the timeout in S3 transfer.
One thing I know and validated is that the concurrency doesn't affect the S3 transfer. So I bumped up concurrency to 24 and with 24 running threads the backup can finish in reasonable time. Full backup which we run on Sundays that backs up around 3TB takes too long (around 16 hours), so I will try to move the database to new instance type, likely i3en.6xlarge and see if this issue goes away.

**Comment by dwsteele** [comment]
> so I will try to move the database to new instance type, likely i3en.6xlarge and see if this issue goes away.

OK, please let us know how that goes.

**Comment by acheccuc-tw** [comment]
We are affected by the same problem, we see frequent 15m pauses during the backup, which considerably stretches the backup time (takes almost twice as long). 
The behaviour changed when we upgraded pgbackrest from version 2.19 to 2.23 (we are on 2.24 now).
Is it _15m_ a value hardcoded somewhere in pgbackrest?
Could you suggest any method for decreasing it or any other workaround?

Thank you

**Comment by dwsteele** [comment]
I'm hoping that this patch 4b24a74afb5c3 will help.  It may also be valuable to allow setting keep-alives to be disabled entirely.  Thoughts?

**Comment by slava-pagerduty** [comment]
Thank you, I have compiled 2.25 release and will give it a try over this weekend.
I see that the patch you referenced above is included in 2.25 release.
Do I need to change tcp-keepalive values in Ubuntu or defaults should be fine?

**Comment by dwsteele** [comment]
The idea of this patch is to set them explicitly in pgBackRest without having to set them at the system level. Any comments on that @marco44?

**Comment by marco44** [comment]
Not really. We're sometimes having similar problems too (with baremetal servers, not amazon, in another datacenter). In our case, when we lost packets, it seemed to point to lost packets somewhere between our hoster and amazon. All sessions died at the same time, and we couldn't establish another one from this or any other server we have in our datacenter, and traceroute died somewhere on the way to S3. But our hoster didn't really seem to care, hence our insistence on having a working keepalive :)

**Comment by dwsteele** [comment]
My hope is the new settings will more aggressively monitor and drop the connection when things go wrong.

I was also thinking it might be a good idea to be able to disable keep-alives and/or configure them.  Or perhaps enabling keep-alives should be the option?

**Comment by marco44** [comment]
Yes, keepalive should improve things, as the "stuck" socket should be detected earlier.

For your second question, yes, the way it's setup in pgbackrest is a bit unusual. The way it's most often seen is to provide the real keepalive parameters as configuration parameters (like PostgreSQL does)

**Comment by acheccuc-tw** [comment]
We have performed a few tests using different Linux kernel versions (on Ubuntu 18.04LTS) as well as trying to tune TCP keepalive settings.
We tested both pgbackrest 2.24 and 2.25.
The summary is that:
- kernel version seems not to make any difference
- setting TCP keepalive quite aggressively prevents the ~15m sleeps. We are currently using:
```
net.ipv4.tcp_keepalive_intvl = 20
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_time = 20
```
- The previous point settings work with 2.24, but with 2.25 we are back to the long sleeps

We have downgraded to 2.24 for the time being

**Comment by slava-pagerduty** [comment]
Thank you @acheccuc-tw. I also tried 2.25 version over this weekend and periodical 15-minute slowdowns were still happening. I'll try some of your suggestions.

**Comment by marco44** [comment]
In 2.25, the "system" values should be ignored, as it will use a hardcoded value, from what I read in the code (STORAGE_S3_TIMEOUT_DEFAULT) to set keepalive. So it should be very similar, except that intvl and time would be 15s.

But I may have found something, @dwsteele : STORAGE_S3_TIMEOUT_DEFAULT isn't 60, it's 60000. And the values expected by setsockopt should be in seconds. Couldn't this be the problem ?

**Comment by slava-pagerduty** [comment]
@dwsteele, I am testing 2.26dev version over this weekend.
So can I now set timeouts in pgbackrest.conf? Do you mind giving me an example of how to set them?
Thank you for working on this!

**Comment by dwsteele** [comment]
You can get option help by running: `pgbackrest help backup`.  The ones you are interested in are `tcp-keep-alive-count`, `tcp-keep-alive-interval`, `tcp-keep-alive-idle`. So, for example: `pgbackrest help backup tcp-keep-alive-count`.

To configure as we meant to have it in 2.25:
```
tcp-keep-alive-idle=15
tcp-keep-alive-count=3
tcp-keep-alive-interval=15
```

Please keep track of what commit you are using to build `pgbackrest`. That will help with debugging.

**Comment by slava-pagerduty** [comment]
Looks like new version of pgbackrest (with  [fix|https://github.com/pgbackrest/pgbackrest/commit/5c6fb88bef242c071fd02671798b296bd65fa47f]) have been pretty stable, and no more 15-minute hickups.
I have tested it on Sunday with full 3.3TB backup to S3 and it took under 3 hours (as before amazon pushed out kernel update).
Here is timing of full db backup to S3 using 24 processes:
```
 type |   start_time_pst    | database_size | backup_size | time_elapsed 
------+---------------------+---------------+-------------+--------------
 FULL | 2020-04-05 04:00:03 | 3325 GB       | 769 GB      | 02:24:28  <-- 2.26dev
 FULL | 2020-03-29 04:00:03 | 3275 GB       | 759 GB      | 17:37:48
 FULL | 2020-03-22 04:00:03 | 3231 GB       | 750 GB      | 17:38:22
 FULL | 2020-03-15 04:00:03 | 3179 GB       | 739 GB      | 16:33:48
 FULL | 2020-03-08 04:00:02 | 3126 GB       | 729 GB      | 16:17:55
 FULL | 2020-03-04 10:35:46 | 3108 GB       | 726 GB      | 16:17:30
 FULL | 2020-03-01 03:00:02 | 3086 GB       | 724 GB      | 17:21:13
 FULL | 2020-02-23 03:00:02 | 3035 GB       | 716 GB      | 16:17:07
```
One thing I noticed, is that I need to add tcp-keep-alive settings to pgbackrest.conf as @dwsteele suggested above. w/o setting in the file, defaults were not helping with timeouts.

**Comment by dwsteele** [comment]
Wow, that's a pretty huge difference. I do wish I knew exactly which kernel change caused the change in behavior.

> One thing I noticed, is that I need to add tcp-keep-alive settings to pgbackrest.conf as @dwsteele suggested above. w/o setting in the file, defaults were not helping with timeouts.

Yeah, the default Linux settings are pretty useless. We decided to mimic Postgres and not set our own defaults, which is what we were trying to do (badly as it turned out) in 2.25.

**Comment by marco44** [comment]
The default is very high for most operating systems, yes. I think it's the same (2 hours) for windows.

**Comment by sean0101n** [comment]
@dwsteele I'm currently seeing this issue in CentOS 7 (CentOS Linux release 7.7.1908 (Core)).   I have two database servers I'm currently backing up (40TB db1, 30TB db2), both have pgbackrest 2.21 installed.  The kernel versions are different:
db1 - no issues during backup, uname -r yields 3.10.0-1062.9.1.el7.x86_64
db2 - 15 minute pauses, uname -r yields 3.10.0-1062.18.1.el7.x86_64

**Comment by dwsteele** [comment]
@sean0101n @slava-pagerduty I tried to reproduce the error on that kernel version but I couldn't get a single error after hours of testing. It seems there is something else going on.

Our current strategy is to move to a non-blocking implementation based on how Postgres does it. But since we still can't repro the issue we'd definitely appreciate some help testing. We plan to have something ready to test tomorrow.

Also, we were thinking of an `auto` option for `sck-keep-alive` where we set some reasonable timeouts based on our `io-timeout`, currently 60 seconds. Thoughts on making `auto` the default? We'd also make `io-timeout` configurable.  `io-timeout` represents the time that we expect to see *some* activity on the network, not the time to transfer an entire file.

**Comment by marco44** [comment]
Yes, having it timeout after 1 minute (or less) makes perfect sense. There's no way we'd like an archiving command to last for hours :)

**Comment by dwsteele** [comment]
> Yes, having it timeout after 1 minute (or less) makes perfect sense.

We definitely want that timeout, but doing it with keep-alives feels like papering over what is arguably a bug in pgBackRest.  Certainly keep-alives were broken in 2.25 but 2.26 fixes that as @slava-pagerduty has demonstrated.

As for the underlying problem, we have prepared a patch using non-blocking sockets in our TLS implementation. That is now available here: https://github.com/pgbackrest/pgbackrest/tree/dev-noblock. This branch has gone through all the same testing we would do for a release, but we are still doing review so it is not all in master.

We feel like this is a better way to implement the 60-second I/O timeout (which we'll expose as an option, too).

@slava-pagerduty Any chance you can test this branch? The idea would be to test it without setting the `tcp-keep-alive*` options to make sure it actually fixes the issue.

**Comment by slava-pagerduty** [comment]
> Any chance you can test this branch? The idea would be to test it without setting the tcp-keep-alive* options to make sure it actually fixes the issue
yep. will do tonight
2.26dev have been running without hiccups for last 10 days or so.

**Comment by dwsteele** [comment]
@slava-pagerduty You are awesome, thank you!

**Comment by slava-pagerduty** [comment]
I  compiled pgbackreast from dev-noblock branch and commented out tcp-keep-alive* settings in config and things look good. No 15-minute hiccups or timeouts in backup.log
version:
`
2020-04-14 11:00:01.239 P00   INFO: backup command begin 2.26dev: --pg1-path=/data/pg-warehouse --process-max=12 --repo1-path=/pgbackrest-repo --repo1-retention-diff=20 --repo1-retention-full=8 --repo1-s3-bucket=pd-pg-warehouse --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-2 --repo1-type=s3 --stanza=pg-warehouse --start-fast --type=diff
`

**Comment by dwsteele** [comment]
Was it any faster? If things are really working I would expect some increase in speed since we are not waiting 60 seconds for the keep-alives. But now we have our own internal timer at 60 seconds so if there's still an issue and we are timing out ourselves there might not be a speed improvement. Still better than where we are now, but it would be nice to know if the problem is solved rather than just mitigated in a different way. Thanks!

**Comment by slava-pagerduty** [comment]
I think it's about the same if comparing to 2.26dev with tcp-keep-alive* settings in config.
I only have incremental backups to test, so testing is limited. I will continue running it with full backup on Sunday.
Attached log with two backups:
2020-04-13 2.26dev with  tcp-keep-alive* settings in config
2020-04-13 2.26dev dev-noblock branch  without  tcp-keep-alive* settings in config
[pg-warehouse-backup.226.dev-noblock.log.gz](https://github.com/pgbackrest/pgbackrest/files/4478037/pg-warehouse-backup.226.dev-noblock.log.gz)

Since incremental backup on second day is 3 times larger, time increased proportionally.
Also I am running backup with 12 threads, so likely shorter timeouts are absorbed by concurrent processes and less pronounced.

**Comment by dwsteele** [comment]
The first run actually seems a bit faster, 220MiB/s rather than 193MiB/s, but of course performance is not a constant thing.

But the retry rate in the second run is much lower, 10% vs 46%, which is pretty encouraging. Something's still up, though, because retry rates on the backups I run hover around 0%.

We did find one more issue that may be causing retries so we'd like to get you to try one more version before we release. We're finishing up the review now and I'll provide a commit from master later today.

**Comment by slava-pagerduty** [comment]
Thanks for your work. I'll try the new commit as soon as you have it and continue testing.

**Comment by dwsteele** [comment]
The commit is ready in master at c88684e2bf3. I posted this earlier but I'm not sure it I never hit send or it got lost. I'll try to repost the original contents in a bit but I just wanted to get you going.

**Comment by dwsteele** [comment]
OK, longer version, again. We have finished reviewing the non-blocking TLS implementation and it is committed to master at c88684e2bf3. We found one issue that might explain why you were seeing higher retry rates that we expected, so we would definitely like you to test the new version if you are able. This is the release candidate so if everything looks good we can release it on Monday.

Please let us know how you would like to appear in the release notes.

Thank you for doing these tests. We would not have been able to get this done without your help.

**Comment by dwsteele** [comment]
Oh, almost forgot.  If you could run the backup with:
```
--log-level-file=detail --log-subprocess
```
That will log the TLS/HTTP statistics for the local processes and give us a better idea of the retry rate during backup file copy.

The main process stays idle for longer between transmissions to S3 so it is more likely to see normal timeouts since S3 will only hold a connection open for so long.

**Comment by slava-pagerduty** [comment]
no problem. will  fetch new master branch and run with two logging parameters

**Comment by slava-pagerduty** [comment]
Tested with latest dev version (last commit c88684e2bf32cef8cc185cca4ef213457b03fa62  from Thu Apr 16 16:05:44 2020 -0400, Non-blocking TLS implementation).
log attached.
[pgbackrest.2020.04.17.zip](https://github.com/pgbackrest/pgbackrest/files/4494794/pgbackrest.2020.04.17.zip)

**Comment by dwsteele** [comment]
Thanks! We'll have a look.

Can you also provide the log from local-1? It should look like `pg-warehouse-backup-local-001.log`

**Comment by slava-pagerduty** [comment]
here you go:
```
cat /var/log/pgbackrest/pg-warehouse-backup-local-001.log 
-------------------PROCESS START-------------------
2020-04-17 04:06:16.830 P00   INFO: backup:local command begin 2.26dev: --no-checksum-page --host-id=1 --log-level-console=off --log-level-file=detail --log-level-stderr=error --log-subprocess --pg1-path=/data/pg-warehouse --process=1 --process-max=12 --remote-type=pg --repo1-path=/pgbackrest-repo --repo1-retention-diff=20 --repo1-retention-full=8 --repo1-s3-bucket=pd-pg-warehouse --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-2 --repo1-type=s3 --stanza=pg-warehouse --start-fast --type=diff
2020-04-17 06:27:12.169 P00 DETAIL: socket statistics: objects 1, sessions 86, retries 0
2020-04-17 06:27:12.169 P00 DETAIL: tls statistics: objects 1, sessions 86, retries 0
2020-04-17 06:27:12.169 P00   INFO: http statistics: objects 1, sessions 86, requests 7198, retries 27, closes 58
2020-04-17 06:27:12.169 P00   INFO: backup:local command end: completed successfully (8455340ms)
```

**Comment by dwsteele** [comment]
OK, this looks pretty similar to the last backup at 187 MiB/s. All the diff backups we've seen have been about half as fast per GiB as the last full backup you posted. I'm not sure that's significant because there are a lot of possible factors. We'll just have to see how the full backup goes on Sunday.

The retry rate of .37% on the local is excellent. The vast majority of these are just closes by S3 because we have been idle a bit too long. We'll need to split these out into a separate category if we want to get a better view of what's going on, but these numbers are pretty much what I've seen when I monitor retries at debug level.

This all looks good so I think we are ready for a release on Monday. I added a few commits to master today to allow `io-timeout` and `sck-block` to be configured. I think these are safe but if you want to do another build for paranoia's sake feel free.

Again, thank you for all your help!

**Comment by slava-pagerduty** [comment]
Sounds good to me too. I'll pull new version a bit later today and test over weekend with full backup.
Will let you know if any issues.
Glad I could help, and thanks for your work. The S3 backup feature is super useful!

**Comment by dwsteele** [comment]
@slava-pagerduty We have the release queued up with what you have tested plus these (fairly) minor commits: 6f41ce1182c34 and 4b28f79c92b49.

So, we are ready to go once we get the thumbs up from you.

Also let is know if you'd like to appear in the release notes as something other than `slava-pagerduty`.

**Comment by slava-pagerduty** [comment]
Full backup (3458.8GB) worked good. 
Here is a summary for last couple of days, including full backup on 2020-04-19:
```
cat /var/log/pgbackrest/pg-warehouse-backup-local-001.log 
-------------------PROCESS START-------------------
2020-04-19 11:00:13.721 P00   INFO: backup:local command begin 2.26dev: --no-checksum-page --host-id=1 --log-level-console=off --log-level-file=detail --log-level-stderr=error --log-subprocess --pg1-path=/data/pg-warehouse --process=1 --process-max=12 --remote-type=pg --repo1-path=/pgbackrest-repo --repo1-retention-diff=20 --repo1-retention-full=8 --repo1-s3-bucket=pd-pg-warehouse --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-2 --repo1-type=s3 --stanza=pg-warehouse --start-fast --type=full
2020-04-19 15:55:33.819 P00 DETAIL: socket statistics: objects 1, sessions 208, retries 0
2020-04-19 15:55:33.819 P00 DETAIL: tls statistics: objects 1, sessions 208, retries 0
2020-04-19 15:55:33.819 P00   INFO: http statistics: objects 1, sessions 208, requests 16045, retries 84, closes 124
2020-04-19 15:55:33.819 P00   INFO: backup:local command end: completed successfully (17720098ms)

-------------------PROCESS START-------------------
2020-04-20 11:00:31.929 P00   INFO: backup:local command begin 2.26dev: --no-checksum-page --host-id=1 --log-level-console=off --log-level-file=detail --log-level-stderr=error --log-subprocess --pg1-path=/data/pg-warehouse --process=1 --process-max=12 --remote-type=pg --repo1-path=/pgbackrest-repo --repo1-retention-diff=20 --repo1-retention-full=8 --repo1-s3-bucket=pd-pg-warehouse --repo1-s3-endpoint=s3.amazonaws.com --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=us-west-2 --repo1-type=s3 --stanza=pg-warehouse --start-fast --type=diff
2020-04-20 12:51:36.264 P00 DETAIL: socket statistics: objects 1, sessions 65, retries 0
2020-04-20 12:51:36.264 P00 DETAIL: tls statistics: objects 1, sessions 65, retries 0
2020-04-20 12:51:36.264 P00   INFO: http statistics: objects 1, sessions 65, requests 5601, retries 16, closes 48
2020-04-20 12:51:36.264 P00   INFO: backup:local command end: completed successfully (6664336ms)
```
I tested with version I grabbed on Friday with latest commit:
```
21a1cf9a2f18cc294474efda064a2ae08cc8d18d 
Fri Apr 17 09:55:40 2020 -0400  
Add sck-block option
```
Thanks for adding me to release notes! You can use my full name: Slava Moudry.

**Comment by dwsteele** [comment]
Well, the full backup looks like it took less than two hours which is better than last week -- more or less what I was hoping for since we don't have to wait for KA timeouts anymore.

Can we get the main log as well: `/var/log/pgbackrest/pg-warehouse-backup.log`?

**Comment by dwsteele** [comment]
Hmmm, no, I was looking at the wrong log. The full backup was almost five hours, which is twice as long as your full backup from 2020-04-05. So all the backups we've seen since that full backup on 2020-04-05 have been twice as slow per GB, even the ones that were run with the same version of 2.26dev before we provided the non-blocking version.

Any chance we could get the log from 2020-04-05 to see if we can spot the difference?

**Comment by slava-pagerduty** [comment]
Sure, Here is full backup log for 2 days (full on 04.19 and incremental on 04.20): [pg-warehouse-backup.log.20200419.gz](https://github.com/pgbackrest/pgbackrest/files/4505838/pg-warehouse-backup.log.20200419.gz)

> the full backup was almost five hours, which is twice as long as your full backup from 2020-04-05
That's true, but I have lowered the number of processes to 12 (from 24 on 2020-04-05), so this is not an issue. The backup time is proportional to data size and I can add more processes to pgbackrest to speed it up at the expense of resources available to queries.

**Comment by slava-pagerduty** [comment]
Here is log of full backups:
```
 type |   start_time_pst    | database_size | backup_size | time_elapsed 
------+---------------------+---------------+-------------+--------------
 FULL | 2020-04-19 04:00:02 | 3458 GB       | 793 GB      | 04:52:34  <-- 2.26dev, process-max=12
 FULL | 2020-04-12 11:11:31 | 3411 GB       | 784 GB      | 02:48:53  <-- 2.26dev, process-max=24
 FULL | 2020-04-05 04:00:03 | 3325 GB       | 769 GB      | 02:24:28  <-- 2.26dev, process-max=24
 FULL | 2020-03-29 04:00:03 | 3275 GB       | 759 GB      | 17:37:48  <-- 2.25
 FULL | 2020-03-22 04:00:03 | 3231 GB       | 750 GB      | 17:38:22
```

**Comment by dwsteele** [comment]
Sure, halving the processes would double the time. It's math! :)

The main log also looks good so I've pushed the release up to integration. It will be in master before too long.

Thanks!

**Comment by dwsteele** [comment]
@sean0101n Have you had a chance to try 2.26 yet and see if it helps your slow server?

**Comment by sean0101n** [comment]
I've been waiting for it to be available through yum install.  Do you know if there's an ETA for it to be available through the yum repo?

**Comment by dwsteele** [comment]
It was pushed last Tuesday. I see 2.26 when I do `yum install pgbackest`.

Devrim did some rearranging a while back -- perhaps you need to update your yum repo?

**Comment by sean0101n** [comment]
yup, I see it now, had to run makecache fast to see it.  I have a planned full backup this Saturday for that database, I'll let you know if I'm still seeing those pauses.

**Comment by sean0101n** [comment]
@dwsteele Our backup has been running since Saturday night (>30TB db) and I haven't seen any pauses yet.  The upgrade to 2.26 seems to have fixed that issue.  Thanks!

**Comment by dwsteele** [comment]
@sean0101n Good news! We'll close this issue now, but let us know if anything doesn't look right when your backup completes.
